development: 
  cloud_name: "hkslfiutm"
  api_key: "838119976279937"
  api_secret: "LKAETLz8SqdrH2ximFW3kF3IfIU"
  secure: true

production:
  cloud_name: "hkslfiutm"
  api_key: "838119976279937"
  api_secret: "LKAETLz8SqdrH2ximFW3kF3IfIU"
  secure: true